# Generated by Django 3.2 on 2021-05-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='leaveDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('regno', models.CharField(max_length=9)),
                ('dept', models.CharField(max_length=3)),
                ('year', models.CharField(max_length=15)),
                ('reason', models.TextField()),
            ],
        ),
    ]
